# Generated by Django 5.2.7 on 2026-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notification'), ('promotion', 'Promotion'), ('vip_upgrade', 'VIP Upgrade'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('recharge_confirmed', 'Recharge Confirmed'), ('settlement', 'Settlement Notification'), ('referral', 'Referral Notification'), ('blog_approved', 'Blog Post Approved'), ('blog_rejected', 'Blog Post Rejected')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('withdrawal', 'Withdrawal'), ('buy_product', 'Buy Product'), ('settlement', 'Settlement Income'), ('promotion_commission', 'Promotion Commission'), ('system_deduction', 'System Deduction'), ('referral_bonus', 'Referral Bonus'), ('vip_reward', 'VIP Reward'), ('blog_reward', 'Blog Post Reward')], max_length=30),
        ),
    ]
