# Generated by Django 5.2.7 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(default='honeypot trap', max_length=255)),
                ('path_hit', models.CharField(blank=True, max_length=255)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='honeypot_ba_ip_addr_e79383_idx')],
            },
        ),
    ]
