# Generated by Django 5.2.7 on 2026-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('email_tried', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Honeypot Attempt',
                'verbose_name_plural': 'Honeypot Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BannedIP',
        ),
    ]
