# Generated by Django 5.2.7 on 2026-06-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='dailyearninglog',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_logs', to='store.userinvestment'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyearninglog',
            unique_together={('investment', 'date')},
        ),
    ]
