# Generated by Django 5.2.7 on 2026-06-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category'),
        ),
        migrations.DeleteModel(
            name='InvestmentCategory',
        ),
    ]
