# Generated by Django 5.2.7 on 2026-06-18 15:30

import blog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of viewer', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent', null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', help_text='Device type', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the post was viewed')),
            ],
            options={
                'verbose_name': 'Blog View',
                'verbose_name_plural': 'Blog Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Blog post content (max 2000 characters)', max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', help_text='Current approval status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured posts appear at the top')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned posts stay at the top')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the post was approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the post was rejected', null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reward amount for approved post', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reward_currency', models.CharField(default='UGX', help_text='Currency code for reward', max_length=10)),
                ('reward_paid', models.BooleanField(default=False, help_text='Whether reward has been paid')),
                ('reward_paid_at', models.DateTimeField(blank=True, help_text='When reward was paid', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of views', validators=[django.core.validators.MinValueValidator(0)])),
                ('like_count', models.IntegerField(default=0, help_text='Number of likes', validators=[django.core.validators.MinValueValidator(0)])),
                ('comment_count', models.IntegerField(default=0, help_text='Number of comments', validators=[django.core.validators.MinValueValidator(0)])),
                ('share_count', models.IntegerField(default=0, help_text='Number of shares', validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the post', max_length=255, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the post was last updated')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the post was published/approved', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admins', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Author of the blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-is_pinned', '-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the like was created')),
                ('user', models.ForeignKey(help_text='User who liked the post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(help_text='Blog post that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Like',
                'verbose_name_plural': 'Blog Likes',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Blog post image (max 5MB)', upload_to=blog.models.blog_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('blog', models.ForeignKey(help_text='Blog post this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Image',
                'verbose_name_plural': 'Blog Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content (max 500 characters)', max_length=500)),
                ('like_count', models.IntegerField(default=0, help_text='Number of likes on this comment', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the comment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the comment was last updated')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment (for replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment')),
                ('user', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(help_text='Blog post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fake', 'Fake/Misleading'), ('copyright', 'Copyright Violation'), ('other', 'Other')], help_text='Reason for report', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details', max_length=500, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the report has been reviewed')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the report was resolved', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the report', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the report was created')),
                ('blog', models.ForeignKey(help_text='Blog post being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.blogpost')),
                ('reporter', models.ForeignKey(help_text='User who made the report', on_delete=django.db.models.deletion.CASCADE, related_name='blog_reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Report',
                'verbose_name_plural': 'Blog Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Reward amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='UGX', help_text='Currency code', max_length=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether reward has been paid')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When reward was paid', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When reward was created')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the reward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_rewards_approved', to=settings.AUTH_USER_MODEL)),
                ('blog', models.OneToOneField(help_text='Blog post that received reward', on_delete=django.db.models.deletion.CASCADE, related_name='reward_record', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Reward',
                'verbose_name_plural': 'Blog Rewards',
                'ordering': ['-created_at'],
            },
        ),
    ]
