# Generated by Django 5.2.7 on 2026-06-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreward',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction record for this reward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_rewards', to='users.transaction'),
        ),
        migrations.AddField(
            model_name='blogreward',
            name='user',
            field=models.ForeignKey(help_text='User who received the reward', on_delete=django.db.models.deletion.CASCADE, related_name='blog_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogview',
            name='blog',
            field=models.ForeignKey(help_text='Blog post that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogview',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who viewed the post (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['user', 'status'], name='blog_blogpo_user_id_338a49_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created_at'], name='blog_blogpo_created_2e77d7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', '-published_at'], name='blog_blogpo_is_feat_1c3903_idx'),
        ),
        migrations.AddIndex(
            model_name='bloglike',
            index=models.Index(fields=['blog', '-created_at'], name='blog_blogli_blog_id_e136e4_idx'),
        ),
        migrations.AddIndex(
            model_name='bloglike',
            index=models.Index(fields=['user', '-created_at'], name='blog_blogli_user_id_4375d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together={('blog', 'user')},
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['blog', '-created_at'], name='blog_blogco_blog_id_b4babf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['user', '-created_at'], name='blog_blogco_user_id_43af83_idx'),
        ),
        migrations.AddIndex(
            model_name='blogreport',
            index=models.Index(fields=['blog', '-created_at'], name='blog_blogre_blog_id_3f97a7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogreport',
            index=models.Index(fields=['is_resolved', '-created_at'], name='blog_blogre_is_reso_ba915a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogreport',
            unique_together={('blog', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', '-viewed_at'], name='blog_blogvi_blog_id_ca2b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['user', '-viewed_at'], name='blog_blogvi_user_id_1d871e_idx'),
        ),
    ]
