# Generated by Django 5.2.7 on 2026-07-04 02:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(help_text='Admin user who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reward amount for approved post. Stays 0.00 while pending — only set by an admin at approval time, and always constrained to UGX 100 - UGX 500,000 (see BlogPost.approve()).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
