# Generated by Django 5.2.7 on 2026-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcomment_user_alter_blogpost_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='reward_paid',
            field=models.BooleanField(default=False, help_text="Whether reward has been credited to the user's commission wallet. Set True automatically inside approve() the moment the credit succeeds."),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reward_paid_at',
            field=models.DateTimeField(blank=True, help_text='When reward was credited', null=True),
        ),
    ]
