# Generated by Django 5.2.7 on 2026-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_reward_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='reward_paid',
            field=models.BooleanField(default=False, help_text="Whether reward has been credited to the user's commission wallet. Set True automatically inside credit_reward_and_notify() the moment the credit succeeds. Also acts as the idempotency guard preventing the same post's reward from being credited twice, no matter how many times approve()/credit_reward_and_notify() get called on it (e.g. from admin actions)."),
        ),
    ]
