# Generated by Django 5.2.7 on 2026-06-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitation', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='users.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionrate',
            unique_together={('level', 'vip_level')},
        ),
        migrations.AddField(
            model_name='invitationclick',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitationclick',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_click', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='invitation.referralrelationship'),
        ),
        migrations.AlterUniqueTogether(
            name='referralrelationship',
            unique_together={('referrer', 'referee', 'level')},
        ),
    ]
